name: du_bii_m6_integrative_bioinfo-2019

channels:
  - conda-forge
  - bioconda
  - lcantini
  - r
  - default

dependencies:

  ## RCRAN packages
  - conda-forge::r-base  >=3.5,< 3.6
  - conda-forge::r-mixomics
  - conda-forge::mixKernel

  ## Bioconda

  ## Other packages
  - lcantini::r-mofa

