name: du_bii_m6_integrative_bioinfo-2019

channels:
  - conda-forge
  - bioconda
  - lcantini
  - default

dependencies:

  ## RCRAN packages
  - bioconda::r-mixkernel=0.3  - conda-forge::r-gprofiler    # functional enrichment 

  ## Other packages
  - bioconda::bioconductor-mixomics=6.6.0
  - bioconda::r-wgcna

  ## lcantini
  - lcantini::r-mofa
