name: du_bii_m6_integrative_bioinfo-2019

channels:
  - bioconda
  - conda-forge
  - lcantini

dependencies:

  ## RCRAN packages
  - conda-forge::r-base  >=3.5,< 3.6
  - conda-forge::r-mixomics
  - bioconda::r-mixkernel 

  ## Bioconda

  ## Other packages
  - lcantini::r-mofa

