name: du_bii_m6_integrative_bioinfo-2019

channels:
  - conda-forge
  - bioconda
  - lcantini
  - default

dependencies:
  - bioconda::bioconductor-mixomics=6.6.0
  - bioconda::r-mixkernel=0.3
  - lcantini::r-mofa
